# Generated by Django 3.0.4 on 2020-03-10 19:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last Name')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('web_address', models.URLField(blank=True, verbose_name='Web Address')),
                ('summary_of_bug', models.TextField(help_text='Enter a brief description of the bug', max_length=1000)),
                ('detail_description_of_bug', models.TextField(help_text='Enter a brief description of the bug', max_length=3000)),
                ('date_of_bug', models.DateField(blank=True, null=True, verbose_name='Date of submission of bug')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('inprogress', 'In Progress'), ('done', 'Done')], default='todo', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='BugComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_submitted', models.TextField(max_length=500)),
                ('date_of_published', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BugUserVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last Name')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('web_address', models.URLField(blank=True, verbose_name='Web Address')),
                ('summary_of_feature', models.TextField(help_text='Enter a brief description of the feature', max_length=1000)),
                ('detail_description_of_feature', models.TextField(help_text='Enter a detail description of the feature', max_length=3000)),
                ('date_of_feature', models.DateField(blank=True, null=True, verbose_name='When do you want it fixed by')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('inprogress', 'In Progress'), ('done', 'Done')], default='todo', max_length=12)),
                ('address_one', models.CharField(default='SOME STRING', max_length=100)),
                ('city', models.CharField(default='SOME STRING', max_length=50)),
                ('state', models.CharField(default='SOME STRING', max_length=2)),
                ('stripe_id', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'subscriber',
            },
        ),
        migrations.CreateModel(
            name='FeatureComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_submitted', models.TextField(max_length=500)),
                ('date_of_published', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureUserVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Feature')),
            ],
        ),
    ]
