# Generated by Django 3.0.4 on 2020-03-10 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='featureuservotes',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featurecomment',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Feature'),
        ),
        migrations.AddField(
            model_name='featurecomment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feature',
            name='user_rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buguservotes',
            name='bug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Bug'),
        ),
        migrations.AddField(
            model_name='buguservotes',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bugcomment',
            name='bug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Bug'),
        ),
        migrations.AddField(
            model_name='bugcomment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
