# Generated by Django 3.0.4 on 2020-04-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200310_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurecomment',
            old_name='feature',
            new_name='bug',
        ),
    ]
