# Generated by Django 3.0.4 on 2020-04-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200407_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='card_cvv',
            field=models.CharField(max_length=120, null=True, verbose_name='Your cvv at back of credit card'),
        ),
        migrations.AddField(
            model_name='feature',
            name='credit_crd_num',
            field=models.CharField(max_length=120, null=True, verbose_name='Please enter in credit card number'),
        ),
        migrations.AddField(
            model_name='feature',
            name='expiring_month_credit_crd',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], max_length=120, null=True, verbose_name='month'),
        ),
        migrations.AddField(
            model_name='feature',
            name='expiring_year_credit_crd',
            field=models.CharField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], max_length=120, null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='address_one',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='feature',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='feature',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
    ]
